### PR TITLE
Fixed all the spaces between units and numbers

### PR DESCRIPTION
**Pull request by rolandFleddermann**
This is the most annoying diff ever, all the lines look (almost) the same, but I replaced all the spaces between numbers and units with narrow non-breaking spaces (unicode character U+202F) as per common style guides.
I was also not very disciplined and fixed one typo in that same process (added a multiplication sign) and made the tot in E_tot mathrm.
I used regular expressions here, so xkcd 1171 https://xkcd.com/1171/ applies, i.e. there might well be new problems in there now.
Mostly did this because it seemed eary and I wanted to test the setup with my personal github account.

### CODE REVIEW

**Comment by paultcochrane** [comment]
I've definitely seen more annoying diffs.  ;-)  There are really three separate changes being applied in this PR and I prefer these in separate commits as this makes the diffs much easier to read, which then makes review also much easier.  However, since you've specified the changes in the commit message, so I think that's ok.

**Review by paultcochrane — CHANGES_REQUESTED** [review]
Why was the heat capacity value changed to 4.0 J/g/K here?  The correct value should be 4.2 J/g/K.

**Review by paultcochrane — CHANGES_REQUESTED** [review]
The heat capacity value was also changed here from 4.2 to 4.0 J/g/K.  I'm pretty sure this should be 4.2 J/g/K.  Is this an error in the suggested changes?

**Review by paultcochrane — CHANGES_REQUESTED** [review]
Why capitalise the 'k' in 'kJ' here?  I think this might be an error in the suggested changes.

**Comment by rolandFleddermann** [comment]
> Why was the heat capacity value changed to 4.0 J/g/K here? The correct value should be 4.2 4.2 J/g/K.

I have no idea. But I'll refer you to my initial comment: I used regular expressions. Something clearly went wrong, I guess I'll try that again...

**Comment by rolandFleddermann** [comment]
That didn't work, I'll start over fresh...

**Pull request closed without merging**
